#!/usr/bin/env groovy
pipeline {
    agent any
    stages{
        stage('Build') {
            agent {
                docker {
                    image 'maven:3-alpine'
                }
            }
            steps {
                sh "mvn package -Dmaven.test.skip=true"
            }
        }
        stage('T2-Test') {
            agent {
                docker {
                    image 'maven:3-alpine'
                }
            }
            steps {
                sh "mvn test"
            }
        }
        stage('Coverage-JaCoCO') {
            step([$class: 'JacocoPublisher',
                  execPattern: 'target/*.exec',
                  classPattern: 'target/classes',
                  sourcePattern: 'src/main/java',
                  exclusionPattern: 'src/test*'
            ])
        }
    }
}