#!/usr/bin/env groovy
pipeline {
    agent any
    stages{
        stage('Build') {
            agent {
                docker {
                    image 'maven:3-alpine'
                }
            }
            steps {
                sh "mvn package -Dmaven.test.skip=true"
            }
        }
        stage('T2-Test') {
            agent {
                docker {
                    image 'maven:3-alpine'
                }
            }
            steps {
                sh "mvn test"
            }
        }

        stage('Build & Generate Test Report') {
            agent {
                docker {
                    image 'maven:3-alpine'
                }
            }
            steps {
                script {
                   try {
                       sh "mvn package"
                   } finally {
                       junit '**/build/test-results/test/*.xml' //make
                       
                   }
                }
            }
        }

       stage('Publish Test Coverage Report') {
           steps {
               step([$class: 'JacocoPublisher',
                   execPattern: '**/build/jacoco/*.exec',
                   classPattern: '**/build/classes',
                   sourcePattern: 'src/main/java',
                   exclusionPattern: 'src/test*'
               ])
           }
       }



    }
}